rootProject.name = 'commerce-msa'

include 'gateway-admin'
include 'gateway-commerce'
include 'service-auth'
include 'service-tenant'
include 'service-metadata'
include 'service-search'
include 'service-catalog'
include 'service-order'
include 'service-pricing'
include 'service-inventory'
include 'service-customer'
include 'service-notification'
include 'service-scheduler'
