services:
  app-blue:
    image: bllue-green-docker-app:latest
    build:
      context: ./app
    environment:
      DEPLOY_COLOR: blue
      DEPLOY_VERSION: ${DEPLOY_VERSION:-local}
    ports:
      - "19081:8080"
    networks:
      - bllue-green-network

  app-green:
    image: bllue-green-docker-app:latest
    build:
      context: ./app
    environment:
      DEPLOY_COLOR: green
      DEPLOY_VERSION: ${DEPLOY_VERSION:-local}
    ports:
      - "19082:8080"
    networks:
      - bllue-green-network

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8098:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/upstreams:/etc/nginx/upstreams
    networks:
      - bllue-green-network

networks:
  bllue-green-network:
    driver: bridge
