apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: commerce
  labels:
    app.kubernetes.io/name: api-gateway
data:
  application.yml: |
    spring:
      cloud:
        gateway:
          server:
            webflux:
              httpclient:
                connect-timeout: 3000
                response-timeout: 5s
    management:
      tracing:
        sampling:
          probability: 1.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  namespace: commerce
  labels:
    app.kubernetes.io/name: account-service
data:
  application.yml: |
    server:
      tomcat:
        threads:
          max: 200
        accept-count: 100
    management:
      tracing:
        sampling:
          probability: 1.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contents-service
  namespace: commerce
  labels:
    app.kubernetes.io/name: contents-service
data:
  application.yml: |
    server:
      tomcat:
        threads:
          max: 200
        accept-count: 100
    management:
      tracing:
        sampling:
          probability: 1.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: commerce
  labels:
    app.kubernetes.io/name: user-service
data:
  application.yml: |
    server:
      tomcat:
        threads:
          max: 200
        accept-count: 100
    management:
      tracing:
        sampling:
          probability: 1.0
