apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - rbac.yml
  - configmaps.yml
  - api-gateway.yml
  - user-service.yml
  - account-service.yml
  - contents-service.yml
  - ingress.yml
  - scaling.yml
  - availability.yml
  - network-policies.yml
