apiVersion: v1
kind: Namespace
metadata:
  name: commerce
  labels:
    app.kubernetes.io/part-of: commerce-msa
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
