plugins {
    id "groovy-gradle-plugin"
}

def springBootVersionValue = providers.gradleProperty("springBootVersion").get()

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation "org.springframework.boot:org.springframework.boot.gradle.plugin:${springBootVersionValue}"
    implementation "io.spring.gradle:dependency-management-plugin:1.1.7"
}

gradlePlugin {
    plugins {
        springBootService {
            id = "com.revy.scaffolding.spring-boot-service"
            implementationClass = "com.revy.scaffolding.SpringBootServiceConventionPlugin"
        }
        springLibrary {
            id = "com.revy.scaffolding.spring-library"
            implementationClass = "com.revy.scaffolding.SpringLibraryConventionPlugin"
        }
    }
}
