spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal_admin
    username: portal
    password: portal1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
