server:
  port: 8080

spring:
  application:
    name: web-api
  datasource:
    url: jdbc:h2:mem:web;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    issuer: order-application
    secret: change-this-secret-key-change-this-secret-key
    access-token-seconds: 3600
