server:
  port: 8081

spring:
  application:
    name: gateway-commerce
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9001
          predicates:
            - Path=/auth/**
        - id: tenant
          uri: http://localhost:9002
          predicates:
            - Path=/tenant/**
        - id: metadata
          uri: http://localhost:9003
          predicates:
            - Path=/metadata/**
        - id: search
          uri: http://localhost:9004
          predicates:
            - Path=/search/**
        - id: catalog
          uri: http://localhost:9010
          predicates:
            - Path=/catalog/**
        - id: order
          uri: http://localhost:9011
          predicates:
            - Path=/order/**
        - id: pricing
          uri: http://localhost:9012
          predicates:
            - Path=/pricing/**
        - id: inventory
          uri: http://localhost:9013
          predicates:
            - Path=/inventory/**
        - id: customer
          uri: http://localhost:9014
          predicates:
            - Path=/customer/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders: "*"

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-should-be-longer-than-32-bytes}
    issuer: commerce-platform
    allowed-roles: ADMIN,CUSTOMER
    public-paths: /auth/**,/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
