server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: transactional-outbox
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:transactional_outbox}
    username: ${DB_USERNAME:sample_user}
    password: ${DB_PASSWORD:sample_pass}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: transactional-outbox-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  kafka:
    order-created-topic: order.created.v1
  outbox:
    fixed-delay: 3000ms
    batch-size: 20
    publish-timeout: 5s
    retry-backoff: 10s
