plugins{
    id 'org.springframework.boot'
}

version='0.0.0'

dependencies {
    implementation(project(":core:common-webmvc"))
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

jar {
    enabled = false
}

bootJar {
    enabled = true
}