spring:
  application:
    name: sample-kafka-integration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trade-instruction-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.samplekafkaintegration.messaging.domain
        spring.json.value.default.type: com.example.samplekafkaintegration.messaging.domain.TradeInstructionMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  kafka:
    trade-topic: trade.instructions.v1
    trade-dlt-topic: trade.instructions.v1.dlt
