spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5433}/${ORDER_DB_NAME:orderdb}
    username: ${ORDER_DB_USERNAME:orderapp}
    password: ${ORDER_DB_PASSWORD:orderapp}
  jpa:
    hibernate:
      ddl-auto: update

