spring:
  application:
    name: order-service
  profiles:
    default: local
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888/config}
      fail-fast: ${CONFIG_SERVER_FAIL_FAST:false}
      import-check:
        enabled: false
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: debug
