org.gradle.parallel=true
org.gradle.workers.max=4
# org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true

### 의존성 버전 정보
springBootVersion=4.1.0
dependencyManagementVersion=1.1.7
jibVersion=3.5.2
springCloudVersion=2025.1.2
opentelemetryVersion=2.28.1

springBootAdminVersion=4.1.1
jkubeVersion=1.19.0

### lib
jacksonAnnotationsVersion=2.19.0
uuidCreatorVersion=5.1.0
commonLang3Version=3.20.0
springDocVersion=3.0.3

# 공통 Jib 기반 이미지
jibBaseImage=eclipse-temurin:21-jre-alpine
