org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8

# 모듈별 애플리케이션 버전
apiGatewayVersion=0.1.0
userServiceVersion=0.1.0
accountServiceVersion=0.1.0
contentsServiceVersion=0.1.0
commonMetricsVersion=0.1.0
commonSecurityVersion=0.1.0

# 환경별 기본 이미지 Registry
localImageRegistry=commerce
devImageRegistry=commerce-dev
stagingImageRegistry=commerce-staging
productionImageRegistry=commerce-production

# 공통 Docker 멀티스테이지 기반 이미지
dockerBuildImage=eclipse-temurin:21-jdk-alpine@sha256:1ff763083f2993d57d0bf374ab10bb3e2cb873af6c13a04458ebbd3e0337dc76
dockerRuntimeImage=eclipse-temurin:21-jre-alpine@sha256:3f08b13888f595cc49edabea7250ba69499ba25602b267da591720769400e08c
