ALTER TABLE users ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE users ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE portfolios ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE portfolios ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE orders ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE orders ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE trades ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE trades ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE positions ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE positions ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE journal_vouchers ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE journal_vouchers ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE journal_vouchers ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE journal_entries ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE journal_entries ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE journal_entries ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';

ALTER TABLE ledger_entries ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE ledger_entries ADD COLUMN created_by VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE ledger_entries ADD COLUMN updated_by VARCHAR(120) NOT NULL DEFAULT 'system';
