plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':platform-core')
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

springBoot {
    mainClass = 'com.revy.mvpbanking.userapi.UserApiApplication'
}
