spring:
  application:
    name: app-1
  profiles:
    default: local

server:
  port: 10000

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
